## Table of Contents

- NumPy
  - How to install numpy
  - Why do we need numpy arrays
  - Differences between NumPy array and Python List
  - Advantages over Python lists
- Functions to Create Arrays
- Common methods and Functions on NumPy array
- Indexing
- Slicing

## 1. Numpy
- It is the fundamental package for scientific computing with Python
- It provides a high-performance multidimensional array object, and tools for working with these arrays
- It has important features as:
  - A powerful N-dimensional array object
  - Sophisticated (broadcasting) functions
  - Useful linear algebra, Fourier transform, and random number capabilities

**How to install numpy?**<br>
1. You can use-<br>
`!pip install numpy`<br>
2. You can import it as-<br>
import numpy as np

In [ ]:
# import the numpy package as np
import numpy as np

### Why do we need Numpy Arrays
- With numpy arrays, mathematical operations are executed more efficiently and with less code compared to Python’s built-in data structures. 
- Hence, numpy arrays are very useful when working with a large data.

### Differences between Numpy Array and Lists
 - Arrays are homogeneous whereas Lists can be homogeneous or heterogeneous
 - Element wise operation is possible in arrays but not possible in lists
 - Arrays are very useful for multi-dimensional data. 

### Advantages over Python lists
- Fast computation
- Consumes less memory
- numpy arrays are more compact as compared to lists.

In [ ]:
# create a Numpy array using arange of size 1000000
my_array = np.arange(1000000)

# create a python list using range of size 1000000
my_list = list(range(1000000))

In [ ]:
# print out execution time for the following

# time required for computations in an array
%time for _ in range(10): my_modified_array = my_array ** 2

# time required for computation in an list    
%time for _ in range(10): my_modified_list = [x ** 2 for x in my_list]

Wall time: 37.5 ms
Wall time: 6.54 s


- From the above result, you can observe that the numpy arrays are faster than python lists.
- Here Wall time, also called wall-clock time, measures the total time to execute a program in a computer.

## 2. Functions to Create Array


**The N-dimensional array**<br>
An easy way to create an array from structures such as a list is to use the `array()` function.

In the example below, first, create two python lists. Then, create numpy arrays out of the created lists.

In [ ]:
# create 2 new lists age and height of 6 people
age = [20,25,26,29,32,70]
height = [5.2,5,5.11,6.1,5.7,5.10]

# create 2 numpy arrays from age and height from the above lists
age = np.array(age)
height = np.array(height)

In [ ]:
## print the 'age' array
age

array([20, 25, 26, 29, 32, 70])

In [ ]:
## print the 'height' array
height

array([5.2 , 5.  , 5.11, 6.1 , 5.7 , 5.1 ])

In [ ]:
## check the type of 'age' and 'height'
print('age:',type(age))
print('height:',type(height))

age: <class 'numpy.ndarray'>
height: <class 'numpy.ndarray'>


**2. An array of evenly spaced numbers**<br>
- The `linspace()` will create an array of evenly spaced numbers over a specified interval.
- Syntax: linspace(start_index, end_index, num_of_elements)

In [ ]:
## create a array of evenly spaced 10 numbers with interval (2,6)
array = np.linspace(2,6,10)
array

array([2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778,
       4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ])

**3. An array of random numbers**<br>
The `random()` function returns random numbers in the half-open interval [0.0, 1.0). The half-open interval includes 0 but excludes 1. The required number of random numbers is passed through the ‘size’ parameter.


In [ ]:
# create 2D array of 3 rows and 2 columns of random numbers
my_array = np.random.random(size = (3,2))

# print the array
my_array

array([[0.30000536, 0.5114459 ],
       [0.36479626, 0.59922201],
       [0.49543821, 0.50604078]])

The `randn()` creates an array of the given shape with random variables from a uniform distribution between (0, 1)

In [ ]:
# create 2D array of 4 rows and 2 columns of random numbers
my_array = np.random.randn(4,2)

# print the array
my_array

array([[ 0.30871369, -0.69046725],
       [-0.4107352 ,  0.80444129],
       [ 0.53605525, -1.27208833],
       [ 0.64960769, -1.68125644]])

The `randint()` returns random integers from low (inclusive) to high (exclusive)

In [ ]:
# create an array of 3 random numbers between 2 and 9
# the randint() will not include 10, the numbers will be generated between 2 and 9 (both inclusive)
my_array = np.random.randint(2,10,3)

# print the array
my_array

array([9, 8, 2])

**4. Create an array using `arange()`**<br>
arange() function creates an array of numbers between the given range

In [ ]:
# create an array of integers between 0 to 10  
# start: start value of interval (inclusive). 0 is the default value
# stop: stop value of interval (exclusive)
# step: returns numbers with given step_size
sequence = np.arange(start = 0, stop = 10, step = 1)

# print the sequence
sequence

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 3. Common methods and functions on NumPy Array

**ndim:**<br>
Prints the dimension (number of axes) of the numpy array

In [ ]:
my_array = np.array([(11,32,23),(34,55,46)])
print('input array:','\n',my_array)
print('dimension:',my_array.ndim)

input array: 
 [[11 32 23]
 [34 55 46]]
dimension: 2


**shape:**<br>
shape: is used to check the shape of the array.

In [ ]:
print('input array:','\n',my_array)
print('shape of the array:',my_array.shape)

input array: 
 [[11 32 23]
 [34 55 46]]
shape of the array: (2, 3)


**size:**<br>
size: is used to check the count of elements in an array

In [ ]:
print('input array:','\n',my_array)
print('shape of the array:',my_array.size)

input array: 
 [[11 32 23]
 [34 55 46]]
shape of the array: 6


**dtype:**<br>
is used to check the datatype of an array.

In [ ]:
print('input array:','\n',my_array)
print('shape of the array:',my_array.dtype)

input array: 
 [[11 32 23]
 [34 55 46]]
shape of the array: int32


**reshape():**<br>
The reshape() is used to change the number of rows and columns of an array without changing the data.<br>

In [ ]:
# create an array
my_array = np.array([(11,32,23),(34,55,46)])
# print the array
# \n: print on a newline
print("The original array:\n", my_array)

# change the shape
my_array_2 = my_array.reshape(3,2)
# print the array
# \n: print on a newline
print("The reshaped array:\n", my_array_2)

The original array:
 [[11 32 23]
 [34 55 46]]
The reshaped array:
 [[11 32]
 [23 34]
 [55 46]]


## 4. Indexing Array

### Index 1D array

In [ ]:
# consider a 1D array
array = np.array([100,200,300,400,500,600])
print('input array:','\n',array)

# retrieve the 1st element
print('1st element:',array[0])

# retrieve the 4th element
print('4th element:',array[3])

# retrieve the last element
print('Last element:',array[-1])

input array: 
 [100 200 300 400 500 600]
1st element: 100
4th element: 400
Last element: 600


### Index 2D array

In [ ]:
# consider a 2D array
array = np.array([[10,34,56],[90,87,66]])
print('input array:','\n',array)

# retrieve the element in the 1st row and 2nd column
a12 = array[0][1]
print('a12:',a12)

# retrieve the elements in the 1st row of all the columns
a1 = array[0]
print('a1:',a1)

input array: 
 [[10 34 56]
 [90 87 66]]
a12: 34
a1: [10 34 56]


## 5. Slicing Array

### Slice 1D array

In [ ]:
# consider a 1D array
array = np.array([90,88,76,54,32,90])
print('input array:','\n',array)

# retrieve the 3rd and 4th element
print('3rd and 4th element:',array[2:4])

# retrieve every 2nd element from 88
print('Every 2nd element:',array[1::2])

# retrieve all the elements before 32
print('Elements before 32:',array[:4])

input array: 
 [90 88 76 54 32 90]
3rd and 4th element: [76 54]
Every 2nd element: [88 54 90]
Elements before 32: [90 88 76 54]


### Slice 2D array

In [ ]:
# consider a 2D array
array = np.array([[10,34,56],[90,87,66]])
print('input array:','\n',array)

# retrieve the elements in the 2nd row and 1st two columns
print('selected elements:',array[1,0:2])

# retrieve the elements in 2nd and 3rd column
print('elements in 2nd & 3rd column:','\n',array[:,1:])

input array: 
 [[10 34 56]
 [90 87 66]]
selected elements: [90 87]
elements in 2nd & 3rd column: 
 [[34 56]
 [87 66]]


### Happy Learning :)